# Header
menu:
  首页: /
  归档: /archives

# avatar
avatar: images/avatar.jpg

# favicon
favicon: /favicon.png

# social
social:
  github: https://github.com
  twitter: https://twitter.com
  weibo: http://weibo.com

# Content
excerpt_link: Read More
fancybox: true


# Automatically Excerpt. Not recommand.
# Please use <!-- more --> in the post to control excerpt accurately.
auto_excerpt:
  enable: true
  length: 150

# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
twitter:
google_plus:
fb_admins:
fb_app_id:
